# 8.3 Singular value decomposition with python

In this section we will decompose a matrix into it's singular value decomposition using python 3. This process is pretty simple.

To get a matrix's singular value decomposition we can use scipy's package.

Specifically;
`from scipy.linalg import svd`

We will also need numpy to.

In [2]:
import numpy as np

Suppose our matrix is the same as the hand written example.

i.e. $$ A = \begin{bmatrix} 1 & 0 \\ 1 & -1 \\ 0 & 1\end{bmatrix}$$

In [3]:
A = np.array([[1,0],[1,-1],[0,1]])
A

array([[ 1,  0],
       [ 1, -1],
       [ 0,  1]])

To find the decompistion of A, we use the scipy function svd.

In [4]:
from scipy.linalg import svd
U, s, VT = svd(A)

This is the matrix U

In [5]:
U

array([[-4.08248290e-01,  7.07106781e-01, -5.77350269e-01],
       [-8.16496581e-01, -5.55111512e-17,  5.77350269e-01],
       [ 4.08248290e-01,  7.07106781e-01,  5.77350269e-01]])

The object s consists of the singular values. The output is not the matrix, just the values!

Note if your matrix U has values such as -5.55111512e-17, just take it to be zero since the number is so small.

In [6]:
s

array([1.73205081, 1.        ])

This is the matrix V.T (the transpose of V)

In [7]:
VT

array([[-0.70710678,  0.70710678],
       [ 0.70710678,  0.70710678]])

It's that simple!

Now one thing we have to keep in mind with forming the matrix Sigma is that it is the same shape as the original matrix, only with singular value on it's diagonal entries.

Thus to form the matrix sigma, we have to first form an empty matrix of the same shape as the original matrix A, and then input the singular values on the diagonal.

Hence we want a matrix sigma of the form (since A is 3x2);

$$ \Sigma = \begin{bmatrix} \sqrt{3} & 0 \\ 0 & 1 \\ 0 & 0 \end{bmatrix}$$

which in python is of the form;

`np.array([[1.73205081,0],[0,1],[0,0]])`

This is done in several steps;

1. Create an empty mxn shaped matrix using numpy's zeros function. This is matrix sigma
2. Set the entries of the diagonal matrix sigma equal to the singular values using the numpy zeros function. The positions in sigma are dependendent upon the original shape of A (see below).

To check our work, we use the numpy dot function to multiply matrices

In [12]:
from numpy import zeros
from numpy import dot

m,n = A.shape[0], A.shape[1]

sigma = np.zeros((m, n))
for i in range(min(m, n)):
    sigma[i, i] = s[i]
a1 = np.dot(U, np.dot(sigma, VT))
print('The original input: \n',A)
print('\n')
print('The matrix after inputting: \n',np.around(a1,1))

The original input: 
 [[ 1  0]
 [ 1 -1]
 [ 0  1]]


The matrix after inputting: 
 [[ 1.  0.]
 [ 1. -1.]
 [-0.  1.]]


We get the same thing (ignore any negative symbols associated with zeros).

# Exercises

For the following matrices, find the singular values using python


Problem 1. $$ \begin{bmatrix} 1 & 0 & 1\\ 1 & -1 & 1\\ 0 & 1 &0\end{bmatrix}$$


Problem 2. $$ \begin{bmatrix} 1 & 2 \\ 2 & 1\end{bmatrix}$$


Problem 3. $$ \begin{bmatrix} 1 & 1 \\ 1 & 1\\ 0 & 0\end{bmatrix}$$


Problem 4. $$ \begin{bmatrix} 1 & -1 \\ 2 & 3\end{bmatrix}$$


Problem 5. $$ \begin{bmatrix} 1 & 1 & 3 \\ 1 & -1 & 3\end{bmatrix}$$


Problem 6. Write a Python function that does the following:
 * Inputs any matrix
 * Finds and prints it's singular values
 * Forms a matrices of U, V.T and sigma (and prints them in their proper shape)
 * Returns a product of U, V.T and sigma that's equal to the original matrix.
 
Problems 7-11: Use the function in problem 6 to input the matrices of problems 1-5 and have an equivalent output (input=output)