# Ch8.4 Pseudoinverses with Python

Now that we've established how to create a pseudo inverse, it's time to code them up in python. In this lesson we will be able to get the pseudo inverse using built in python functions, and also demonstrate that we can get it using the SVD process we did in the SVD python lesson.

To perform pseudoinverses, we can use the `numpy.linalg.pinv` function from numpy.

In [22]:
import numpy as np
#consider the matrix from the hand written example done previously;
A = np.array([[1,0],[1,-1],[0,1]],dtype=np.int64)
A

array([[ 1,  0],
       [ 1, -1],
       [ 0,  1]])

In [18]:
#we input our matrix that we want the inverse for into the function
A_pinv = np.linalg.pinv(A)
print(A_pinv)

[[ 0.66666667  0.33333333  0.33333333]
 [ 0.33333333 -0.33333333  0.66666667]]


which is the same as before;

$$A^{+}=\begin{bmatrix} 2/3 & 1/3 & 1/3 \\ 1/3 & -1/3 & 2/3\end{bmatrix}$$

Which equals our original calculation from the previous section.

Now what does the left hand product of A and it's pseudoinverse equal?

$$AA^{+}=?$$

In [21]:
AAp = np.around(np.dot(A,A_pinv),decimals=5)
AAp

array([[ 0.66667,  0.33333,  0.33333],
       [ 0.33333,  0.66667, -0.33333],
       [ 0.33333, -0.33333,  0.66667]])

$$AA^{+}=\begin{bmatrix} 2/3 & 1/3 & 1/3 \\ 1/3 & 2/3 & -1/3\\ 1/3 & -1/3 & 2/3\end{bmatrix}$$

Now what about $$A^{+} A = ?$$

In [15]:
np.around(np.dot(A_pinv,A),decimals=5)

array([[ 1., -0.],
       [-0.,  1.]])

$$A^{+} A= \begin{bmatrix} 1 & 0 \\ 0 & 1\end{bmatrix}$$

# Exercises

For the following matrices, find the pseudoinverse, and both of the  products;

$$A^{+} A $$

$$AA^{+}$$


Problem 1. $$ \begin{bmatrix} 1 & 0 & 1\\ 1 & -1 & 1\\ 0 & 1 &0\end{bmatrix}$$



Problem 2. $$ \begin{bmatrix} 1 & 2 \\ 2 & 1\end{bmatrix}$$


Problem 3. $$ \begin{bmatrix} 1 & 1 \\ 1 & 1\\ 0 & 0\end{bmatrix}$$


Problem 4. $$ \begin{bmatrix} 1 & -1 \\ 2 & 3\end{bmatrix}$$


Problem 5. $$ \begin{bmatrix} 1 & 1 & 3 \\ 1 & -1 & 3\end{bmatrix}$$